version: '3.8'
services:
  sample-book-app-dev:
    build: .
    image: nenonesa/sample-book-app:latest
    container_name: sample-book-app-dev
    ports:
      - 1010:1050
  sample-book-app-stg:
    build: .
    image: nenonesa/sample-book-app:latest
    container_name: sample-book-app-stg
    ports:
      - 2020:1050
  sample-book-app-prd:
    build: .
    image: nenonesa/sample-book-app:latest
    container_name: sample-book-app-prd
    ports:
      - 3030:1050


# docker run -p 5555:1050 --rm --name sample-book-app-dev sample-book-app
