# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "Building docker image.."
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "Deployment triggered on DEV environment.. "
  api-tests-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "API Tests triggered against DEV environment.. "
  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "Deployment triggered on STG environment.. "
  api-tests-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "API Tests triggered against STG environment.. "
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "Deployment triggered on PRD environment.. "
  api-tests-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step description
        run: echo "API Tests triggered against PRD environment.. "
        